import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Outfit, Inter, Poppins } from 'next/font/google';
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const outfit = Outfit({
    subsets: ["latin"],
    weight: ["100", "400", "700", "900"],
});
const inter = Inter({ weight: ['500'], subsets: ['latin'] });
const poppins = Poppins({ weight: ['100','400','700'], subsets: ['latin'] });


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}